version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/school-dismissal
    environment:
      - MYSQLHOST=db
      - MYSQLDATABASE=school_dismissal
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=school_dismissal
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
